### ISSUE TITLE
debugging messages when creating a new activity

### ISSUE THREAD

**Issue by danmarsden** [Palumdo/moodle-mod_guestquiz#4]
Warning: Attempt to read property "id" on null in/www/moodle/mod/guestquiz/mod_form.php on line 69

Deprecated: str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated in /www/moodle/mod/guestquiz/mod_form.php on line 69

first one looks like you should be using something like if (!empty()) instead of == '') and the 2nd one looks like a PHP 8 issue

**Comment by Palumdo** [comment]
Hi, 
If check if the id is empty and display a different message.

Thank you for your help and review.

Have a nice day.

Dominique.
